name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0  # Adjust according to your Ruby version

      # Step 3: Install dependencies (e.g., using bundler for Ruby)
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install  # Ensure rubocop is installed through Gemfile

      # Step 4: Run validation (RuboCop for code style validation)
      - name: Run RuboCop for code style validation
        run: |
          bundle exec rubocop || echo "RuboCop style violations found, but continuing build."

      # Step 5: Run tests (e.g., using RSpec for Ruby, adjust for your testing framework)
      - name: Run tests
        run: |
          bundle exec rspec || echo "Test failures found, but continuing build."

      # Step 6: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 7: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 8: Build and push Docker image to Docker Hub
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
